/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BurgerMenuApp;

import javax.swing.JOptionPane;

/**
 *
 * @author Encarni
 */
public class BurgerMenuApp extends javax.swing.JFrame {

    /**
     * Creates new form BurgerMenuApp
     */
    public BurgerMenuApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btgHamburguesa = new javax.swing.ButtonGroup();
        btgPan = new javax.swing.ButtonGroup();
        btgPatatas = new javax.swing.ButtonGroup();
        btgBebida = new javax.swing.ButtonGroup();
        btgReparto = new javax.swing.ButtonGroup();
        panPrincipal = new javax.swing.JPanel();
        lblMenuBasico = new javax.swing.JLabel();
        lblHamburguesa = new javax.swing.JLabel();
        panHamburguesa = new javax.swing.JPanel();
        jrbPollo = new javax.swing.JRadioButton();
        jrbCerdo = new javax.swing.JRadioButton();
        jrbTernera = new javax.swing.JRadioButton();
        jrbVegana = new javax.swing.JRadioButton();
        lblPan = new javax.swing.JLabel();
        panPan = new javax.swing.JPanel();
        jrbNormal = new javax.swing.JRadioButton();
        jrbIntegral = new javax.swing.JRadioButton();
        jrbCenteno = new javax.swing.JRadioButton();
        lblPatatas = new javax.swing.JLabel();
        panPatatas = new javax.swing.JPanel();
        jrbFritas = new javax.swing.JRadioButton();
        jrbGajo = new javax.swing.JRadioButton();
        jrbCaseras = new javax.swing.JRadioButton();
        lblBebida = new javax.swing.JLabel();
        panBebida = new javax.swing.JPanel();
        jrbCola = new javax.swing.JRadioButton();
        jrbNaranja = new javax.swing.JRadioButton();
        jrbLimon = new javax.swing.JRadioButton();
        jrbAgua = new javax.swing.JRadioButton();
        jrbCerveza = new javax.swing.JRadioButton();
        lblOpExtra = new javax.swing.JLabel();
        panOpExtra = new javax.swing.JPanel();
        cbxHamburguesaDoble = new javax.swing.JCheckBox();
        cbxExtraQueso = new javax.swing.JCheckBox();
        cbxExtraPatatas = new javax.swing.JCheckBox();
        lblSalsas = new javax.swing.JLabel();
        panSalsas = new javax.swing.JPanel();
        lblKetchup = new javax.swing.JLabel();
        spnKetchup = new javax.swing.JSpinner();
        lblBarbacoa = new javax.swing.JLabel();
        spnBarbacoa = new javax.swing.JSpinner();
        lblMostaza = new javax.swing.JLabel();
        spnMostaza = new javax.swing.JSpinner();
        lblThai = new javax.swing.JLabel();
        spnThai = new javax.swing.JSpinner();
        jrbDomicilio = new javax.swing.JRadioButton();
        jrbRecogidaLocal = new javax.swing.JRadioButton();
        btnCalcular = new javax.swing.JButton();
        lblPrecio = new javax.swing.JLabel();
        lblIva = new javax.swing.JLabel();
        lblPvp = new javax.swing.JLabel();
        ftxtPrecio = new javax.swing.JFormattedTextField();
        ftxtIva = new javax.swing.JFormattedTextField();
        ftxtPvp = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Burguer Menu APP");
        setResizable(false);

        lblMenuBasico.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblMenuBasico.setText("Menú básico (8 €):");

        lblHamburguesa.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblHamburguesa.setText("Hamburguesa");

        panHamburguesa.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panHamburguesa.setPreferredSize(new java.awt.Dimension(129, 119));

        btgHamburguesa.add(jrbPollo);
        jrbPollo.setText("Pollo");

        btgHamburguesa.add(jrbCerdo);
        jrbCerdo.setText("Cerdo");

        btgHamburguesa.add(jrbTernera);
        jrbTernera.setText("Ternera (+1€)");

        btgHamburguesa.add(jrbVegana);
        jrbVegana.setText("Vegana (+1€)");

        javax.swing.GroupLayout panHamburguesaLayout = new javax.swing.GroupLayout(panHamburguesa);
        panHamburguesa.setLayout(panHamburguesaLayout);
        panHamburguesaLayout.setHorizontalGroup(
            panHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panHamburguesaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbTernera)
                    .addComponent(jrbVegana)
                    .addComponent(jrbCerdo)
                    .addComponent(jrbPollo))
                .addContainerGap())
        );
        panHamburguesaLayout.setVerticalGroup(
            panHamburguesaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panHamburguesaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbPollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbCerdo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbTernera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbVegana)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        lblPan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPan.setText("Pan");

        panPan.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panPan.setPreferredSize(new java.awt.Dimension(129, 119));

        btgPan.add(jrbNormal);
        jrbNormal.setText("Normal");

        btgPan.add(jrbIntegral);
        jrbIntegral.setText("Integral");

        btgPan.add(jrbCenteno);
        jrbCenteno.setText("Centeno");

        javax.swing.GroupLayout panPanLayout = new javax.swing.GroupLayout(panPan);
        panPan.setLayout(panPanLayout);
        panPanLayout.setHorizontalGroup(
            panPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbNormal)
                    .addComponent(jrbIntegral)
                    .addComponent(jrbCenteno))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        panPanLayout.setVerticalGroup(
            panPanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPanLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jrbNormal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbIntegral)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbCenteno)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblPatatas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblPatatas.setText("Patatas");

        panPatatas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panPatatas.setPreferredSize(new java.awt.Dimension(129, 119));

        btgPatatas.add(jrbFritas);
        jrbFritas.setText("Fritas");

        btgPatatas.add(jrbGajo);
        jrbGajo.setText("Gajo");

        btgPatatas.add(jrbCaseras);
        jrbCaseras.setText("Caseras (+1€)");

        javax.swing.GroupLayout panPatatasLayout = new javax.swing.GroupLayout(panPatatas);
        panPatatas.setLayout(panPatatasLayout);
        panPatatasLayout.setHorizontalGroup(
            panPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPatatasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrbFritas)
                    .addComponent(jrbGajo)
                    .addComponent(jrbCaseras))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        panPatatasLayout.setVerticalGroup(
            panPatatasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPatatasLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jrbFritas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbGajo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jrbCaseras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblBebida.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblBebida.setText("Bebida");

        panBebida.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panBebida.setPreferredSize(new java.awt.Dimension(430, 41));

        btgBebida.add(jrbCola);
        jrbCola.setText("Cola");

        btgBebida.add(jrbNaranja);
        jrbNaranja.setText("Naranja");

        btgBebida.add(jrbLimon);
        jrbLimon.setText("Limón");

        btgBebida.add(jrbAgua);
        jrbAgua.setText("Agua");

        btgBebida.add(jrbCerveza);
        jrbCerveza.setText("Cerveza");

        javax.swing.GroupLayout panBebidaLayout = new javax.swing.GroupLayout(panBebida);
        panBebida.setLayout(panBebidaLayout);
        panBebidaLayout.setHorizontalGroup(
            panBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jrbCola, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jrbNaranja)
                .addGap(26, 26, 26)
                .addComponent(jrbLimon)
                .addGap(28, 28, 28)
                .addComponent(jrbAgua)
                .addGap(27, 27, 27)
                .addComponent(jrbCerveza)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panBebidaLayout.setVerticalGroup(
            panBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panBebidaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panBebidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbCola)
                    .addComponent(jrbNaranja)
                    .addComponent(jrbLimon)
                    .addComponent(jrbAgua)
                    .addComponent(jrbCerveza))
                .addContainerGap())
        );

        lblOpExtra.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblOpExtra.setText("Opciones extra/adicionales");

        panOpExtra.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panOpExtra.setPreferredSize(new java.awt.Dimension(187, 105));

        cbxHamburguesaDoble.setText("Hamburguesa doble (+2€)");

        cbxExtraQueso.setText("Extra de queso (+0,50€)");

        cbxExtraPatatas.setText("Extra de patatas (+1€)");

        javax.swing.GroupLayout panOpExtraLayout = new javax.swing.GroupLayout(panOpExtra);
        panOpExtra.setLayout(panOpExtraLayout);
        panOpExtraLayout.setHorizontalGroup(
            panOpExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panOpExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbxExtraQueso)
                    .addComponent(cbxExtraPatatas)
                    .addComponent(cbxHamburguesaDoble))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panOpExtraLayout.setVerticalGroup(
            panOpExtraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panOpExtraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cbxHamburguesaDoble)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxExtraQueso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbxExtraPatatas)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        lblSalsas.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSalsas.setText("Salsas (+0,50€ cada una)");

        panSalsas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lblKetchup.setText("Ketchup");

        spnKetchup.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lblBarbacoa.setText("Barbacoa");

        spnBarbacoa.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lblMostaza.setText("Mostaza");

        spnMostaza.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        lblThai.setText("Thai");

        spnThai.setModel(new javax.swing.SpinnerNumberModel(0, 0, 10, 1));

        javax.swing.GroupLayout panSalsasLayout = new javax.swing.GroupLayout(panSalsas);
        panSalsas.setLayout(panSalsasLayout);
        panSalsasLayout.setHorizontalGroup(
            panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSalsasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSalsasLayout.createSequentialGroup()
                        .addComponent(lblKetchup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panSalsasLayout.createSequentialGroup()
                        .addComponent(lblBarbacoa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panSalsasLayout.createSequentialGroup()
                        .addComponent(lblThai)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panSalsasLayout.createSequentialGroup()
                        .addComponent(lblMostaza)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(spnThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panSalsasLayout.setVerticalGroup(
            panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panSalsasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panSalsasLayout.createSequentialGroup()
                        .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMostaza)
                            .addComponent(spnMostaza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblThai)
                            .addComponent(spnThai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panSalsasLayout.createSequentialGroup()
                        .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(spnKetchup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblKetchup))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panSalsasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblBarbacoa)
                            .addComponent(spnBarbacoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        btgReparto.add(jrbDomicilio);
        jrbDomicilio.setText("Reparto a domicilio");

        btgReparto.add(jrbRecogidaLocal);
        jrbRecogidaLocal.setText("Recogida en local (-20% dto.)");

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        lblPrecio.setText("PRECIO");

        lblIva.setText("IVA (21%)");

        lblPvp.setText("P.V.P");

        ftxtPrecio.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        ftxtIva.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        ftxtPvp.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getCurrencyInstance())));

        javax.swing.GroupLayout panPrincipalLayout = new javax.swing.GroupLayout(panPrincipal);
        panPrincipal.setLayout(panPrincipalLayout);
        panPrincipalLayout.setHorizontalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addComponent(panOpExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblSalsas)
                                    .addComponent(panSalsas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(lblMenuBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBebida, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOpExtra)
                            .addComponent(panBebida, javax.swing.GroupLayout.DEFAULT_SIZE, 427, Short.MAX_VALUE)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panHamburguesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHamburguesa))
                                .addGap(20, 20, 20)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPan)
                                    .addComponent(panPan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(panPatatas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblPatatas)))))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jrbDomicilio)
                            .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(ftxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblPrecio)))
                        .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addComponent(jrbRecogidaLocal))
                            .addGroup(panPrincipalLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIva)
                                    .addComponent(ftxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPvp)
                                    .addComponent(ftxtPvp, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        panPrincipalLayout.setVerticalGroup(
            panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMenuBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHamburguesa)
                    .addComponent(lblPan)
                    .addComponent(lblPatatas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(panHamburguesa, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panPan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panPatatas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblBebida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBebida, 40, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOpExtra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(panOpExtra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panPrincipalLayout.createSequentialGroup()
                        .addComponent(lblSalsas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panSalsas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbDomicilio)
                    .addComponent(jrbRecogidaLocal))
                .addGap(18, 18, 18)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPrecio)
                    .addComponent(lblIva)
                    .addComponent(lblPvp))
                .addGap(3, 3, 3)
                .addGroup(panPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtIva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtPvp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        
        double precio = 8;
        double iva;
        double pvp;
        //Opciones obligatorias
        //Comprueba que se ha elegido un tipo de hamburguesa
        if(jrbPollo.isSelected() || jrbCerdo.isSelected() || jrbTernera.isSelected() || jrbVegana.isSelected()){
            if(jrbTernera.isSelected() || jrbVegana.isSelected()){
                precio += 1;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe elegir un tipo de hamburguesa", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Comprueba que se ha elegido un tipo de pan
        if(!jrbNormal.isSelected() && !jrbIntegral.isSelected() && !jrbCenteno.isSelected()){
            JOptionPane.showMessageDialog(this, "Debe elegir un tipo de pan", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Comprueba que se ha elegido un tipo de patatas
        if(jrbFritas.isSelected() || jrbGajo.isSelected() || jrbCaseras.isSelected()){
            if(jrbCaseras.isSelected()){
                precio += 1;
            }
        }else{
            JOptionPane.showMessageDialog(this, "Debe elegir un tipo de patatas", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        //Comprueba que se ha elegido una bebida
        if(!jrbCola.isSelected() && !jrbNaranja.isSelected() && !jrbLimon.isSelected() && !jrbAgua.isSelected() && !jrbCerveza.isSelected()){
            JOptionPane.showMessageDialog(this, "Debe elegir una bebida", "Atención", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        //Opciones extra/adicionales 
        if(cbxHamburguesaDoble.isSelected()){
            precio += 2;
        }
        if(cbxExtraQueso.isSelected()){
            precio += 0.5;
        }
        if(cbxExtraPatatas.isSelected()){
            precio += 1;
        }
        //Cuenta la cantidad de salsa seleccionada    
        int cantidadSalsa = (Integer)spnKetchup.getValue() + (Integer)spnBarbacoa.getValue() +
                            (Integer)spnMostaza.getValue() + (Integer)spnThai.getValue();
        precio += (double)cantidadSalsa * 0.5;        
        //Tipo de reparto
        if(!jrbDomicilio.isSelected() && !jrbRecogidaLocal.isSelected()){
           JOptionPane.showMessageDialog(this, "Debe elegir el tipo de reparto", "Atención", JOptionPane.WARNING_MESSAGE);
           return; 
        }else if(jrbRecogidaLocal.isSelected()){
            precio -= precio * 20 / 100;
        }      
        //Calcula los precios
        iva = precio * 21 / 100;
        pvp = precio + iva;
        ftxtPrecio.setValue(precio);
        ftxtIva.setValue(iva);
        ftxtPvp.setValue(pvp);
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BurgerMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BurgerMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BurgerMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BurgerMenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BurgerMenuApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgBebida;
    private javax.swing.ButtonGroup btgHamburguesa;
    private javax.swing.ButtonGroup btgPan;
    private javax.swing.ButtonGroup btgPatatas;
    private javax.swing.ButtonGroup btgReparto;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JCheckBox cbxExtraPatatas;
    private javax.swing.JCheckBox cbxExtraQueso;
    private javax.swing.JCheckBox cbxHamburguesaDoble;
    private javax.swing.JFormattedTextField ftxtIva;
    private javax.swing.JFormattedTextField ftxtPrecio;
    private javax.swing.JFormattedTextField ftxtPvp;
    private javax.swing.JRadioButton jrbAgua;
    private javax.swing.JRadioButton jrbCaseras;
    private javax.swing.JRadioButton jrbCenteno;
    private javax.swing.JRadioButton jrbCerdo;
    private javax.swing.JRadioButton jrbCerveza;
    private javax.swing.JRadioButton jrbCola;
    private javax.swing.JRadioButton jrbDomicilio;
    private javax.swing.JRadioButton jrbFritas;
    private javax.swing.JRadioButton jrbGajo;
    private javax.swing.JRadioButton jrbIntegral;
    private javax.swing.JRadioButton jrbLimon;
    private javax.swing.JRadioButton jrbNaranja;
    private javax.swing.JRadioButton jrbNormal;
    private javax.swing.JRadioButton jrbPollo;
    private javax.swing.JRadioButton jrbRecogidaLocal;
    private javax.swing.JRadioButton jrbTernera;
    private javax.swing.JRadioButton jrbVegana;
    private javax.swing.JLabel lblBarbacoa;
    private javax.swing.JLabel lblBebida;
    private javax.swing.JLabel lblHamburguesa;
    private javax.swing.JLabel lblIva;
    private javax.swing.JLabel lblKetchup;
    private javax.swing.JLabel lblMenuBasico;
    private javax.swing.JLabel lblMostaza;
    private javax.swing.JLabel lblOpExtra;
    private javax.swing.JLabel lblPan;
    private javax.swing.JLabel lblPatatas;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JLabel lblPvp;
    private javax.swing.JLabel lblSalsas;
    private javax.swing.JLabel lblThai;
    private javax.swing.JPanel panBebida;
    private javax.swing.JPanel panHamburguesa;
    private javax.swing.JPanel panOpExtra;
    private javax.swing.JPanel panPan;
    private javax.swing.JPanel panPatatas;
    private javax.swing.JPanel panPrincipal;
    private javax.swing.JPanel panSalsas;
    private javax.swing.JSpinner spnBarbacoa;
    private javax.swing.JSpinner spnKetchup;
    private javax.swing.JSpinner spnMostaza;
    private javax.swing.JSpinner spnThai;
    // End of variables declaration//GEN-END:variables
}
